# Generated by Django 2.2.24 on 2022-03-03 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0066_auto_20220223_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedThumbnailLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='curated_thumbs')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
    ]
